export default [
  "Automatik",
  "Bluetooth",
  "Einparkhilfe (v/h)",
  "Klimaautomatik",
  "LED Scheinwerfer",
  "Navi",
  "Sitzheizung",
  "Sound System",
  "Alufelgen",
  "Klimaanlage",
  "Tempomat",
  "Einparkhilfe hinten",
  "7 Sitze",
  "Anh�ngerkupplung",
  "Xenon Scheinwerfer",
  "Lederausstattung",
  "Lenkradheizung",
  "Navi via App",
  "5 T�ren",
  "Keyless Go",
  "LED-Tagfahrlicht",
  "R�ckfahrkamera",
  "Spurwechselassistent",
  "Spurhalteassistent",
  "Tempomat mit ACC",
  "Head-Up Display",
  "Einparkhilfe vorne",
  "Sitzverstellung elektrisch",
];
